default: player1 player2

player1: player1.c stringGame.c
	gcc -std=c99 -o player1 player1.c stringGame.c

player2: player2.c stringGame.c
	gcc -std=c99 -o player2 player2.c stringGame.c

.PHONY: default