default: player1 player2

player1: player1.c string_game.c
	gcc -std=c99 -o player1 player1.c string_game.c

player2: player2.c string_game.c
	gcc -std=c99 -o player2 player2.c string_game.c

.PHONY: default
